"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Command_1 = require("./Command");
const Device_1 = require("./Device");
const RemoteController_1 = require("./RemoteController");
const tv = new Device_1.TV();
const stereo = new Device_1.Stereo();
const turnOnCommand = new Command_1.TurnOnCommand(tv);
const turnOffCommand = new Command_1.TurnOffCommand(tv);
const adjustVolumeStereoCommand = new Command_1.AdjustVolumeCommand(stereo);
const changeChannelTVCommand = new Command_1.ChangeChannelCommand(tv);
const remote = new RemoteController_1.RemoteController();
remote.setCommand(turnOnCommand);
remote.pressButton();
remote.setCommand(adjustVolumeStereoCommand);
remote.pressButton();
remote.setCommand(turnOffCommand);
remote.pressButton();
remote.setCommand(changeChannelTVCommand);
remote.pressButton();
